language: java

jdk:
  - oraclejdk8

env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "YUTiNNTQDWreGEs3TDsdLgE0qQXfmNHIc+plSNwkRRaoG2WzFeFbTFLhkYLW9hiVLZG62snWBwbWl7kXtDlkYNz7iPSj8nBC7e8NFPLxYsH7+jV1c5NMUDGohOuwkjYee4D8S4eUIr3nAk3QOjUk6nSQYKUYJkcHtpcOO3lAgvsa44Gj5v7vSsorzioepIWtKJZO0AmMYraP4eZI6cBK4GbgDOtago7qDII95NZoALcxNeWoSwa9/FzGB10Wx9pFksOQ7WLQ5Kzs6VNKdnvlV6VNo2xgD9spnENs2w9yk2dULbp9z4RI5Lby96bYVw0MZwM1wsr+ri7zCXirv8lZombM3L/VLYgXoGB+HnVVvif78e74JUnPWZcdc6Is7Vhms92vvJcKTWgurIOabJN3/18Pvi2iXfyy0X6zS61VV4a9nGONKy42KfpoJ5FosFNPzYwXyOIrQAhmuFafmCRVJko8aUzLnKkxTbzrPIQ4ox8CTnh/lwoOtd+DHpSOvUqKurPr8qzeouF04T7TH9bKhwJhlOm1fS2d7XaJ20fk/nkesWe7ZPsofm9/9S2p1lKkNaK4Tfbp0vPGECzWFcgy9m8TRPQU5OkCg5j3GJRzMAby/UhIqYz4zGEf4/2r4mEdoOtP3je+sLBVeVDyzMzajlhHSCv1YB1heFQQy/UYXS0="
    # OSSRH_JIRA_PASSWORD
    - secure: "CDpmbG/VGbRal0cbfudOGBjfAG9xLiDyKzprmBDw1BVRpCR3FxvpRZ192whonkZmx4fBW0GlXpLwd7kvlrgLdBBc+JYE9Pv6lO40D/jmkwYiB84bm4/Y2gGL+JGxKip/I5GVysQDsEY7vYqRvxc75683J4h6SMmAtJNunwVObSesX4CqF9+pE8mWr/pHOrArbyQor9BkgsF9o1/Gxxy00WS8E57Hrs9Bl5qre5Llok/YYjc83dsHhxtkyH+oZzlUtXBo1W2fN3PH53SdiHgsL17XaRGEKY3XHC5UNl98kNrTonsXcQ1t6YlO+8lFYSdE1AGDB553xBAap4P5hxUMJqwtSBd/Sn8szUIUfd931ueGgWYxKCzYYJ1584z1oj2VIocD4GPNDYPBNn+vvIE37x+idgStUFoIiJbMgSwc4BV7DUJRqXzv0edof7iDaVQHKDHasJwD84JB1Mg+iDk7PrRTi4nqyqazjDnKfG6dW5T3HiOJg/L5QW8/e1kwOX9B5tIsUDHxUw6i/uacNe34bxw2sxSZpDfq64YhmGXoHqrLtWaJCLCYn3M/2ZeV1t758UAllqbmX+inHhWXvdQ9uqDuuzT0X3k2/GoZdNCpy2Doo5YLRxYqtx3gZnyhdevCyfoJLCS1Z5ggCvhJy0mL0ZPeBE7q00Z+tQMfPsW6TtU="
    # GPG_KEY_NAME
    - secure: "H0a6pmaADo0eBK2ov5Kkzw0aHTKOnYOn8E0CPz1cHnSA15U/q+QBtC68wcuBszhK+ZssAATgbirKRpFYgw0m2LNgVAWPP1tmO6+oX1yynDY157Fao87gfOS0xYeWUK97MR1sYfQlfOrjPyCYap5Va5GNZRNHoObXjeLm3s4ZC3ioBd17mv9H/21W6Clej7b4DhQSLQ1a5PnqzmfyfzqW4FjJo94FpcCVHB9iaw/8yH/nFDpI+cLVUbIjpnZw5dL38fbiYniwtg/EDlzXeC9/+AkC5FJUQN0NQfBv8WujREKDaRypt9xaQd58jp/lhgULx5kxPS0ebkxuHl3o671+S5ymtFMoj6ESyVksh1leRbEzuJtjGEB20i2KbcRf9/hJD1ozwnx0HBp83o2Oxik/4gqX31tk+yK0qWM3lYTLbnF4DxbZbZarc1H1RfAhtj3fHUFsbZem+H/yabCiUHQVsmSt5hDPMXZq1QXHJzFpQaWtcgb7aMnMIWv5UaMOPBkGZvVn3/BfsAmn3X0SOU3iKxRCXTVRPrqccIwhhzvt8tuWV3FLJW7G7OK2VCEq1YVzl+uRUHXivIo+Sfp/x0kgMDmNNr4AkqhZ+N4qEz5HXoQ0ChssGG8mSdYXePLXnXc1ljHwYvnUF91CRG49yvDz0J5CvrJ3XLPubeoAvSv7wL0="
    # GPG_PASSPHRASE
    - secure: "Zc/caXJQa4nuJ9kBk4p+ouN2u2BL1YAlbFiubie19HPfhGsm6CsWOLJGHjFOirFNpubF4mMtrKsQTBtZCTKzrZI7ifSnm7+cI8ZWpaYdN1S2mHjZgKRTG+1fDa1LkQjq8+9qZIVk5eriE1TMb4yNUJOdw3T9O9IxBk5H9IjXWsdt1Y7sF3IMBdjoejlTIhy6UZ0GHhd8xaAs5KmlpmE1aNBWLIcRSCwpXHRwy9Gvm0umiYPdP6/OA+qgeTNaiMlny1xDWbgs8d5YQRS0xwkb3wgRvMzKLRx60WDfLEXFM70gK0jNQC1E0/6v3wGm8X86uA/Ys9hVMrLFAkkjTYzL32lWm3AFTC9pjr426jd3ckhnoKDMIi0+ZIAjrqTGAi8IjAJS9PH7rTiGVuqjv36p9XLvmYJkX8cn8M7LfCUXYmWch7nqnig0qmIyULb4bjkP3G/4egF54TKajZxVx3OslAXdLIMl9sJRWJ271gepsYmjPaCEph4fCESNAxL6vjx4qeM4u1sC4Xmfaj+LZp1Zrq2gJvwb6zjcWXrwjLsWZeHGCNJm7uSvImuUJlAbr6AMci+8v2SPatsrc5F2Uhheczo57MXe0Xpp05Zp/eiC91OZRnE3y1de6w7PSt0usiLSpGEeqGHu9xzrPUGo8SQi8IpEHcnffB1MUi+bfPP5MS0="


deploy:
  - provider: script
    script: cd/deploy.sh
    on:
      tags: true

cache:
  directories:
    - ~/.m2/repository
